<?php echo $this->menu; ?>

<?php
$data = [];
/*
 * KONEC TESTOVACÍCH DAT 
 */

if( !empty( $this->bannery ) ) 
{
    foreach( $this->bannery as $banner )
    {
        $parsedTime = $banner["parsedTime"];
        $banner = $banner["data"];

        $casy = explode( "|" , $banner->cas );
        foreach( $casy as $index=>$cas )
        {
            if( $index === 0 ) 
            {
                $data[ $cas ][ $banner->pozice ] = [ "data" => $banner , "span" => 1 , "parsedTime" => $parsedTime ];
                $beingSpaned = $cas;
            }
            elseif( $casy[ $index-1 ] != $cas-2 )
            {
                $data[ $cas ][ $banner->pozice ] = [ "data" => $banner , "span" => 1 , "parsedTime" => $parsedTime ];
                $beingSpaned = $cas;
            }
            else
            {
                $data[ $cas ][ $banner->pozice ] = "span";
                $data[ $beingSpaned ][ $banner->pozice ]["span"]++;
            }
        }

    } 
}
?>

<div class="shadow area">
    <h3>Zakoupení reklamního místa na stránkách</h3>

    <table class="schedule table-hover">
        <tr>
            <th width="4%">Čas</th>
            <th width="24%">Banner #1</th>
            <th width="24%">Banner #2</th>
            <th width="24%">Banner #3</th>
            <th width="24%">Banner #4</th>
        </tr>
<?php for( $time = 0 ; $time < 24 ; $time += 2) : ?>
            <tr>
                <td><?php echo $time . ":00"; ?></td>
                <?php for( $pos = 1 ; $pos < 5 ; $pos++ ) : ?>
                
                    <?php $banner = @$data[ $time ][ $pos ]; ?>
                    
                    <?php if( isset( $banner["data"] ) && $this->user == $banner["data"]->nick ) : ?>
                        <!--
                            Vlastníkem je uživatel
                        --> 
                        <td rowspan="<?php echo $data[ $time ][ $pos ]["span"]; ?>"><button class="btn btn-info">Váš banner</button></td>
                    <?php elseif( isset( $banner["data"] ) ) : ?>
                        <!--
                            Schválený banner
                        --> 
                        <td rowspan="<?php echo $data[ $time ][ $pos ]["span"]; ?>"><button class="btn btn-danger">Obsazeno</button></td>
                    <?php elseif( isset( $banner ) and $banner === "span" ) : ?>
                        <!--
                            Vynechávka protože předchozí banner přesahuje
                        -->
                    <?php else : ?>
                        <!--
                            Volno
                        --> 
                        <td><button id="<?php echo $pos . "-" . $time; ?>" class="btn btn-success">Volné</button></td>
                    <?php endif; ?>
                <?php endfor; ?>
            </tr>
        <?php endfor; ?>
    </table>
</div>

<div id="objednavka" class="shadow area hidden" >
    <h3>Objednat banner</h3>
    <form action="http://localhost/trinec_cz/profil/pay" method="post">
        <table class="table-form">
            <tr>
                <td> Číslo banneru
                <td> <strong id="banner_number"></strong>
            <tr>
                <td> Čas
                <td> <strong id="banner_time"></strong>
            <tr>
                <td> Celkem hodin za den
                <td> <strong id="banner_sum"></strong>
            <tr>
                <td> Týdnů
                <td>
                    <select name="form_weeks" id="weeks">
                        <?php for( $x = 1 ; $x <= 5 ; $x++ ) : ?>
                            <option value="<?= $x ?>"> <?= $x ?> </option>
                        <?php endfor; ?>
                    </select>
            <tr>
                <td>Cena
                <td><strong id="banner_price"></strong>
            <tr>
                    <input type="hidden" name="banner" id="form_banner">
                    <input type="hidden" name="time" id="form_time">
                    <td> <td> <input type="submit" class="btn btn-info">
        </table>
    </form>
</div>

<div class="shadow area hidden" >
    <h3>Zakoupené bannery</h3>
</div>

<script>
var Times = new Array( );

$(document).ready( function( ) {
    
    $("#weeks").change(
        function() {
            $( '#banner_price' ).text( Times.length * 2 * 90 * parseInt( $( '#weeks' ).val() ) + " Kč" );
        }
    );
    
    $(".btn").click( function( event ) {

        if( $(this).hasClass("btn-success") )
        {
            /*
             * vyčištění když klikne na jiný sloupec
             */
            for( key in Times )
            {
                tempData = $(Times[ key ]).prop("id").split("-");
                data = $(this).prop("id").split("-");

                if( data[0] !== tempData[ 0 ] )
                {
                    Times = new Array( );
                    $(".btn-warning").html("Volné");
                    $(".btn-warning").removeClass("btn-warning").addClass("btn-success");
                    break;
                }
            }
            /*
             * zarazeni do objednávky
             */
            $(this).removeClass("btn-success").addClass("btn-warning");
            $(this).html("Vybráno");
            Times.push( this );
        }
        else if( $(this).hasClass("btn-warning") )
        {
            /*
             * vyrazeni
             */
            for( var key in Times )
            {
                if( Times[ key ] === this )
                {
                    Times.splice( key , 1 );
                    $(this).removeClass("btn-warning").addClass("btn-success");
                    $(this).html("Volné");
                    break;
                }
            }


        }
        
        if( Times.length > 0 )
        {
            $( '#banner_time' ).text( '' );
            $( '#banner_sum' ).text( Times.length * 2 + " hodin" );
            $( '#banner_price' ).text( Times.length * 2 * 90 * parseInt( $( '#weeks' ).val() ) + " Kč" );
            
            var ids = [];
            $.each( Times, function( id, value ) {
                var split = $(value).attr('id').split('-');
                if( split[1].length === 1 ) {
                    split[1] = "0" + split[1];
                }
                ids.push( split[0] + "-" + split[1] );
                
            });
            ids.sort();
            var i = 1;
            $( '#form_time' ).val( '' );
            $.each( ids, function( id, value ) {
                var time = value.split('-');
                $( '#form_time' ).val( $( '#form_time' ).val(  ) + time[1] + "|" );
                if( id === 0 ) {
                    $( '#banner_number' ).text( time[0] );
                    $( '#form_banner' ).val( time[0] );
                }
                var text = $( '#banner_time' ).text();
                var to = parseInt(time[1]) + 2;
                if( to < 10 ) {
                    to = "0" + to;
                }
                to = to + ":00 ";
                    
                var append = time[1] + ":00 - " + to;
                
                if( text.slice(-6, -1) === time[1] + ":00" ) {

                    $( '#banner_time' ).text( text.slice( 0, text.length - 9 ) + " - " + to );
                } else {
                    $( '#banner_time' ).append( append );
                }
            });
            
            
            $("#objednavka").fadeIn( );
            //informace o objednávce
            /*
             * array Times
             */
            
        }
        else
        {
            $("#objednavka").fadeOut( );
            //informace o objednávce
        }
    });
    
});    
</script>

</div>
