<?php echo $this->menu; ?>

<?php 
$data = [];
/*
 * TESTOVACÍ DATA
 */
$temp = [
    new Application\Model\Banner( [ 
        'autor_id'    => 1,
        'url'         => null,
        'img'         => null,
        'doba'        => 2,
        'pozice'      => 1,
        'vlozeno'     => 0,
        'potvrzeno'   => 2,
        'cas'         => "0|2|4",
        'aktivni'     => 1,
    ] ),
    new Application\Model\Banner( [ 
        'autor_id'    => 1,
        'url'         => null,
        'img'         => null,
        'doba'        => 2,
        'pozice'      => 2,
        'vlozeno'     => 0,
        'potvrzeno'   => 0,
        'cas'         => "8|10|12",
        'aktivni'     => 1,
    ] ),
    new Application\Model\Banner( [ 
        'autor_id'    => 1,
        'url'         => null,
        'img'         => null,
        'doba'        => 2,
        'pozice'      => 3,
        'vlozeno'     => 0,
        'potvrzeno'   => 0,
        'cas'         => "8",
        'aktivni'     => 1,
    ] ),
    new Application\Model\Banner( [ 
        'autor_id'    => 1,
        'url'         => null,
        'img'         => null,
        'doba'        => 2,
        'pozice'      => 4,
        'vlozeno'     => 0,
        'potvrzeno'   => 2,
        'aktivni'     => 1,
    ] ),
];

$this->bannery = $temp;
/*
 * KONEC TESTOVACÍCH DAT 
 */

if( !empty( $this->bannery ) ) 
{
    foreach( $this->bannery as $banner )
    {
        $casy = explode( "|" , $banner->cas );
        foreach( $casy as $index=>$cas )
        {
            if( $index === 0 ) 
            {
                $data[ $cas ][ $banner->pozice ] = [ "data" => $banner , "span" => 1 ];
                $beingSpaned = $cas;
            }
            elseif( $casy[ $index-1 ] != $cas-2 )
            {
                $data[ $cas ][ $banner->pozice ] = [ "data" => $banner , "span" => 1 ];
                $beingSpaned = $cas;
            }
            else
            {
                $data[ $cas ][ $banner->pozice ] = "span";
                $data[ $beingSpaned ][ $banner->pozice ]["span"]++;
            }
        }

    } 
}


?>
<div class="shadow area">
    <h3>Zakoupení reklamního místa na stránkách</h3>

    <table class="schedule table-hover">
        <tr>
            <th width="4%">Čas</th>
            <th width="24%">Banner #1</th>
            <th width="24%">Banner #2</th>
            <th width="24%">Banner #3</th>
            <th width="24%">Banner #4</th>
        </tr>
        <?php for( $time = 0 ; $time < 24 ; $time += 2) : ?>
            <tr>
                <td><?php echo $time . ":00"; ?></td>
                <?php for( $pos = 1 ; $pos < 5 ; $pos++ ) : ?>
                
                    <?php $banner = @$data[ $time ][ $pos ]; ?>
               
                    <?php if( isset( $banner["data"] ) and $banner["data"] instanceof Application\Model\Banner ) : ?>
                        <!--
                            Zabraný prostor
                        -->                        
                        <td rowspan="<?php echo $banner["span"]; ?>"><button class="btn btn-danger">Zabráno</button></td>
                    <?php elseif( isset( $banner ) and $banner === "span" ) : ?>
                        <!--
                            Vynechávka protože banner přesahuje
                        -->
                    <?php else : ?>
                        <!--
                            Volno
                        --> 
                        <td><button id="<?php echo $pos . ":" . $time; ?>" class="btn btn-success">Volné</button></td>
                    <?php endif; ?>
                <?php endfor; ?>
            </tr>
        <?php endfor; ?>
    </table>
</div>

<div id="objednavka" class="shadow area hidden" >
    <h3>Objednat banner</h3>
</div>

<div class="shadow area hidden" >
    <h3>Zakoupené bannery</h3>
</div>

<script>
var Times = new Array( );    
    
$(document).ready( function( ) {
    $(".btn").click( function( event ) {

        if( $(this).hasClass("btn-success") )
        {
            /*
             * vyčištění když klikne na jiný sloupec
             */
            for( key in Times )
            {
                tempData = $(Times[ key ]).prop("id").split(":");
                data = $(this).prop("id").split(":");

                if( data[0] !== tempData[ 0 ] )
                {
                    Times = new Array( );
                    $(".btn-warning").html("Volné");
                    $(".btn-warning").removeClass("btn-warning").addClass("btn-success");
                    break;
                }
            }
            /*
             * zarazeni do objednávky
             */
            $(this).removeClass("btn-success").addClass("btn-warning");
            $(this).html("Vybráno");
            Times.push( this );
        }
        else if( $(this).hasClass("btn-warning") )
        {
            /*
             * vyrazeni
             */
            for( var key in Times )
            {
                if( Times[ key ] === this )
                {
                    Times.splice( key , 1 );
                    $(this).removeClass("btn-warning").addClass("btn-success");
                    $(this).html("Volné");
                    break;
                }
            }
            $(this).removeClass("btn-warning").addClass("btn-success");
            $(this).html("Volné");
        }
        
        if( Times.length > 0 )
        {
            $("#objednavka").fadeIn( );
            //informace o objednávce
            /*
             * array Times
             */
        }
        else
        {
            $("#objednavka").fadeOut( );
            //informace o objednávce
        }
    });
    
});    
</script>

</div>
