<div class="area shadow">
    <h3>Váš profil</h3>
        <table class="table-form">
            <form method="get" onsubmit="return update( 'jmeno' )">
                <tr>
                    <td>Jméno</td>
                    <td><input type="text" id="jmeno" value="<?= $this->user->jmeno ?>" placeholder="Zadejte Vaše jméno"></td>
                    <td> <input type="submit" id="jmeno_btn" value="Změnit" class="btn btn-info hid"> </td>
                </tr>
            </form>
            
            <form method="get" onsubmit="return update( 'prijmeni' )">
                <tr>
                    <td>Přijmení</td>
                    <td><input type="text" id="prijmeni" value="<?= $this->user->prijmeni ?>" placeholder="Zadejte Vaše přijmení"></td>
                    <td> <input type="submit" id="prijmeni_btn" value="Změnit" class="btn btn-info hid"> </td>
                </tr>
            </form>            
            
            <form method="get" onsubmit="return update( 'display' )">
                <tr>
                    <td>Zobrazovat u příspěvků jméno a přijmení?</td>
                    <td><input type="checkbox" id="display"  <?php if( $this->user->display == 1 ) echo "checked"; ?>></td>
                    <td><input type="submit" id="display_btn" value="Změnit" class="btn btn-info hid"> </td>
                </tr>
            </form>
            
            <form method="get" onsubmit="return update( 'email' )">
                <tr>
                    <td>Email</td>
                    <td><input type="text" id="email" value="<?= $this->user->email ?>" placeholder="Zadejte Váš email"></td>
                    <td> <input type="submit" id="email_btn" value="Změnit" class="btn btn-info hid"> </td>
                </tr>
            </form>
            
            <form method="get" onsubmit="return update( 'telefon' )">
                <tr>
                    <td>Telefonní číslo</td>
                    <td><input type="text" id="telefon" value="<?= $this->user->telefon ?>" placeholder="Zadejte Vaše telefonní číslo"></td>
                    <td> <input type="submit" id="telefon_btn" value="Změnit" class="btn btn-info hid"> </td>
                </tr>
            </form>
            
            <form method="get" onsubmit="return update( 'adresa' )">
                <tr>
                    <td>Adresa</td>
                    <td><input type="text" id="adresa" value="<?= $this->user->adresa ?>" placeholder="Zadejte Vaši adresu"></td>
                    <td> <input type="submit" id="adresa_btn" value="Změnit" class="btn btn-info hid"> </td>
                </tr>
            </form>
        </table>
</div>

<div class="shadow area">
    <h3>Zakopení místa pro bannery</h3>
</div>

<script type="text/javascript"> 
 	function update( row ) {
        var value = $( '#' + row ).val();
        
        if( $('#' + row).is(':checked') && row === 'display' ) {
            value = 1;
        } else if( row === 'display' ) {
            value = 0;
        }
        
        $.post("/trinec_cz/profil/edit?row=" + row + "&value=" + value, { },
            function(obj) {
                $( "#" + row + "_btn" ).css("visibility", "hidden");
            }
        );
        return false;
    }
    $(document).ready(function(){
        $("input").on( "keypress change",
            function() {
                $( "#" + $(this).attr('id') + "_btn" ).css("visibility", "visible");
            }
        );
    });
</script>