<?php echo $this->menu; ?>

<div class="area shadow">
    <h3>Váš profil</h3>
        <table class="table-form">
            <form onsubmit="return update( 'jmeno' )">
                <tr>
                    <td width="36%">Jméno</td>
                    <td width="36%"><input name="jmeno" type="text" id="jmeno" value="<?= $this->user->jmeno ?>" placeholder="Zadejte Vaše jméno"></td>
                    <td width="16%"><button style="display: none;" type="submit" id="jmeno_btn" class="btn btn-info hid">Změnit</button></td>
                </tr>
            </form>
            
            <form onsubmit="return update( 'prijmeni' )">
                <tr>
                    <td>Přijmení</td>
                    <td><input type="text" id="prijmeni" value="<?= $this->user->prijmeni ?>" placeholder="Zadejte Vaše přijmení"></td>
                    <td><button style="display: none;" type="submit" id="prijmeni_btn" class="btn btn-info hid">Změnit</button></td>
                </tr>
            </form>            
            
            <form onsubmit="return update( 'display' )">
                <tr>
                    <td>Zobrazovat u příspěvků jméno a přijmení?</td>
                    <td><input type="checkbox" id="display"  <?php if( $this->user->display == 1 ) echo "checked"; ?>></td>
                    <td><button style="display: none;" type="submit" id="display_btn" class="btn btn-info hid">Změnit</button></td>
                </tr>
            </form>
            
            <form onsubmit="return update( 'email' )">
                <tr>
                    <td>Email</td>
                    <td><input type="text" id="email" value="<?= $this->user->email ?>" placeholder="Zadejte Váš email"></td>
                    <td><button style="display: none;" type="submit" id="email_btn" class="btn btn-info hid">Změnit</button></td>
                </tr>
            </form>
            
            <form onsubmit="return update( 'telefon' )">
                <tr>
                    <td>Telefonní číslo</td>
                    <td><input type="text" id="telefon" value="<?= $this->user->telefon ?>" placeholder="Zadejte Vaše telefonní číslo"></td>
                    <td><button style="display: none;" type="submit" id="telefon_btn" class="btn btn-info hid">Změnit</button></td>
                </tr>
            </form>
            
            <form onsubmit="return update( 'adresa' )">
                <tr>
                    <td>Adresa</td>
                    <td><input type="text" id="adresa" value="<?= $this->user->adresa ?>" placeholder="Zadejte Vaši adresu"></td>
                    <td><button style="display: none;" id="adresa_btn" class="btn btn-info hid">Změnit</button></td>
                </tr>
            </form>
        </table>
</div>

<script type="text/javascript"> 
 	function update( row /*form*/ ) { 
        var value = $( '#' + row ).val();
        
        if( $('#' + row).is(':checked') && row === 'display' ) {
            value = 1;
        } else if( row === 'display' ) {
            value = 0;
        }
        
        $.post( _URL + "profil/edit", { 'row': row, 'value': value },
            function(obj) {                        
                $( "#" + row + "_btn" ).removeClass('btn-info').addClass('btn-success');
                $( "#" + row + "_btn" ).fadeOut( 1000 );
            }
        );
        return false;
    }
    
    $(document).ready(function(){
        $("input").on( "keyup change",
            function() {
                if( $(this).val() === $(this).prop("defaultValue") )
                {
                    $( "#" + $(this).attr('id') + "_btn" ).hide( );
                }
                else 
                {
                    $( "#" + $(this).attr('id') + "_btn" ).show( );
                }
            }
        );
    });
</script>