<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Třinec.cz')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/layout.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.js'), 'text/javascript')
            ->prependFile($this->basePath('js/load.js'), 'text/javascript')
            ->prependFile('http://code.jquery.com/jquery.min.js', 'text/javascript')
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div id="page">
            <header class="shadow width">
                <div id="header-top">
                    <a href="/" class="leave" ><h1 style="float: left">Třinec.cz</h1></a>
                    <input placeholder="Hledat" id="search" type="text">
                </div>
                <nav>
                    <a class="animate leave" href="">domů</a>
                    <a class="animate leave" href="">pizza</a>
                    <a class="animate leave" href="">inzerce</a>
                    <a class="animate leave" href="">firmy</a>
                    <a class="animate leave" href="">diskuze</a>
                    <a class="animate leave" href="">články</a>
                    <a id="login" class="animate" href="/login">login</a>
                </nav>
                <div id="header-banner"></div>
            </header>
            <div id="content">
                <div class="shadow" id="banner-left"></div>
                <div class="shadow" id="banner-right"></div>
                <div class="width" id="container">
                    <?php echo $this->content; ?>
                </div>
            </div>
            <footer>

            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
