<?php echo $this->menu; ?>

<?php 
$data = [];

$this->bannery;
if( !empty( $this->bannery ) ) 
{
    foreach( $this->bannery as $banner )
    {
        $parsedTime = $banner["parsedTime"];
        $banner = $banner["data"];

        $casy = explode( "|" , $banner->cas );
        foreach( $casy as $index=>$cas )
        {
            if( $index === 0 ) 
            {
                $data[ $cas ][ $banner->pozice ] = [ "data" => $banner , "span" => 1 , "parsedTime" => $parsedTime ];
                $beingSpaned = $cas;
            }
            elseif( $casy[ $index-1 ] != $cas-2 )
            {
                $data[ $cas ][ $banner->pozice ] = [ "data" => $banner , "span" => 1 , "parsedTime" => $parsedTime ];
                $beingSpaned = $cas;
            }
            else
            {
                $data[ $cas ][ $banner->pozice ] = "span";
                $data[ $beingSpaned ][ $banner->pozice ]["span"]++;
            }
        }

    } 
}

?>
<div class="shadow area">
    <h3>Přehled</h3>
    <table class="schedule table-hover">
        <tr>
            <th width="4%">Čas</th>
            <th width="24%">Banner #1</th>
            <th width="24%">Banner #2</th>
            <th width="24%">Banner #3</th>
            <th width="24%">Banner #4</th>
        </tr>
        <?php for( $time = 0 ; $time < 24 ; $time += 2) : ?>
            <tr>
                <td><?php echo $time . ":00"; ?></td>
                <?php for( $pos = 1 ; $pos < 5 ; $pos++ ) : ?>
                
                    <?php $banner = @$data[ $time ][ $pos ]; ?>
                
                    <?php if( isset( $banner["data"] ) and !$banner["data"]->aktivni ) : ?>
                        <!--
                            Neschválený bannner
                        -->                        
                        <td rowspan="<?php echo $banner["span"]; ?>"><button value="<?php echo $pos . "-" . $time; ?>" class="btn btn-warning"><?php echo $banner["data"]->nick; ?> (Čeká)</button></td>
                    <?php elseif( isset( $banner["data"] ) ) : ?>
                        <!--
                            Schválený banner
                        --> 
                        <td rowspan="<?php echo $data[ $time ][ $pos ]["span"]; ?>"><button value="<?php echo $pos . "-" . $time; ?>" class="btn btn-info"><?php echo $banner["data"]->nick; ?> (<?php echo date("j. n. Y", $banner["data"]->potvrzeno ); ?>)</button></td>
                    <?php elseif( isset( $banner ) and $banner === "span" ) : ?>
                        <!--
                            Vynechávka protože předchozí banner přesahuje
                        -->
                    <?php else : ?>
                        <!--
                            Volno
                        --> 
                        <td><button class="btn btn-success">Volné</button></td>
                    <?php endif; ?>
                <?php endfor; ?>
            </tr>
        <?php endfor; ?>
    </table>
</div>
<?php foreach( $data as $time=>$positions ) : ?>
    <?php foreach( $positions as $pos=>$banner ) : ?>
        <?php if( $banner === "span" ) continue; ?>
        <div style="margin-bottom: 20px" id="editace-<?php echo $pos . "-" . $time; ?>" class="editace shadow area hidden" >
            <h3>Informace o banneru</h3>
            <table class="table-form">
                <tr>
                    <td width="46%">Jméno žadatele</td>
                    <td width="46%">
                        <?php echo !empty( $banner["data"]->jmeno ) ? $banner["data"]->jmeno . " " . $banner["data"]->prijmeni : $banner["data"]->nick; ?>
                    </td>
                </tr>
                <tr>
                    <td>Odkaz na adresu</td>
                    <td><a href="<?php echo $banner["data"]->url; ?>"><?php echo $banner["data"]->url; ?></a></td>
                </tr>
                <tr>
                    <td>Obrázek</td>
                    <td><?php echo $banner["data"]->img; ?></td>
                </tr>
                <tr>
                    <td>Doba v týdnech</td>
                    <td><?php echo $banner["data"]->doba; ?></td>
                </tr>
                <tr>
                    <td>Čas</td>
                    <td><?php echo $banner["parsedTime"]; ?></td>
                </tr>
                <tr>
                    <td>Pozice</td>
                    <td><?php echo $banner["data"]->pozice; ?></td>
                </tr>
                <tr>
                    <td>Přidáno</td>
                    <td><?php echo date( "j. n. Y" ,$banner["data"]->vlozeno ); ?></td>
                </tr>
                <tr>
                    <td>Stav</td>
                    <td>
                        <?php if( $banner["data"]->aktivni ) : ?>
                            Schváleno <?php echo date( "j. n. Y" , $banner["data"]->potvrzeno ); ?>
                        <?php else : ?>
                            Čeká na schválení
                        <?php endif; ?>   
                    </td>
                </tr>
                <tr>
                    <td style="text-align: center;" colspan="2">
                        <?php if( $banner["data"]->aktivni ) : ?>
                            <button onclick="update( <?php echo $banner["data"]->id; ?> , 0 , 0 )" class="btn btn-danger">Deaktivovat</button>
                        <?php else : ?>
                            <button onclick="update( <?php echo $banner["data"]->id; ?> ,  1 , <?php echo time(); ?> )" class="btn btn-success">Schválit</button>
                        <?php endif; ?>                    
                    </td>
                </tr>
            </table>
        </div>
    <?php endforeach; ?>
<?php endforeach; ?>

<script>

$(document).ready( function( ) {
    
    $(".btn-warning,.btn-info").click( function( ) {
        var Button = this;
        $(".editace").each( function( ) {
            $(this).fadeOut( 500 );
        });
        window.setTimeout( function( ) {
            $("#editace-" + Button.value).fadeIn( 500 , function ( ) {
                $("html,body").animate({
                    scrollTop: $("#editace-"+ Button.value).offset().top - 200
                }, 1000 );
            });
        } , 500 );
    });
    
    $(window).on( "mousewheel" , function( ) {
        $("html,body").stop();
    })
});

function update( id , aktivni , cas )
{
    $.post( _URL + "admin/editbanner" , { id: id, aktivni: aktivni , cas: cas },
        function(obj) {
            location.href = _URL + "admin/bannery";
        }
    );
}

    
</script>