<?php $this->menu( $this->basePath("inzerce") , array( 
          '' => 'vypis',
          'pridat' => 'přidat nový',
      ) , '' ); ?>

<?php $this->messenger( $this->succes , $this->notice , $this->error ); ?>


<div id="kategorie">
    <?php foreach( $this->kategorie as $row ) : ?>
        <?php if( $row["data"]->typ !== 'inzeraty' ) continue; ?>
        <ul class="category shadow">
            <li class="heading"><?php echo $row["data"]->nazev; ?></li>
            <?php if( !empty( $row["children"] ) ) : foreach( $row["children"] as $child ) : ?>    
                <li><?php echo $child["data"]->nazev; ?></li>
            <?php endforeach; endif;?>
        </ul>
    <?php endforeach; ?>
</div>