<?php echo $this->menu; ?>

<div id="kategorie">
    <?php foreach( $this->kategorie as $row ) : ?>
        <?php if( $row["data"]->typ !== 'inzeraty' ) continue; ?>
        <ul class="category shadow">
            <li class="heading"><?php echo $row["data"]->nazev; ?></li>
            <?php if( !empty( $row["children"] ) ) : foreach( $row["children"] as $child ) : ?>    
                <li><?php echo $child["data"]->nazev; ?></li>
            <?php endforeach; endif;?>
        </ul>
    <?php endforeach; ?>
</div>