<div class="shadow" id="inzeraty">
    <h3>Inzeráty</h3>
    <table style="margin: 5px; width: 430px;" class="table table-hover">
        <tr><td>test<td>test
        <tr><td>test<td>test
        <tr><td>test<td>test
        <tr><td>test<td>test
        
    </table>
</div>
<div class="shadow" id="firmy">
    <h3>Firmy</h3>
    
</div>
<div class="shadow" id="diskuze">
    <h3>Poslední příspěvky v diskuzi</h3>
    
</div>
<div class="shadow" id="clanky">
    <h3>Poslední články</h3>
    
</div>