<div class="shadow" id="inzeraty">
    <h3>Vybrané inzeráty</h3>
    <table class="table-stripped table-hover">
        <tr>
            <td class="bold">Kočárek
                <acronym title="Luxury"><div class="icon-luxury"></div></acronym>
                <acronym title="Firemní inzerát"><div class="icon-firm"></div></acronym>
            <td class="number">500,-
        <tr>
            <td class="bold">Auto
                <acronym title="Luxury"><div class="icon-luxury"></div></acronym>
            <td class="number">50 000,-
        <tr>
            <td class="bold">Byt
                <acronym title="VIP"><div class="icon-vip"></div></acronym>
            <td class="number">500 000,-
        <tr>
            <td class="bold">Protein
                <acronym title="VIP"><div class="icon-vip"></div></acronym>
            <td class="number">500,-
        <tr>
            <td class="bold">Hrnec
                <acronym title="VIP"><div class="icon-vip"></div></acronym>
            <td class="number">500,-
        <tr>
            <td class="bold">Auto
                <acronym title="VIP"><div class="icon-vip"></div></acronym>
                <acronym title="Firemní inzerát"><div class="icon-firm"></div></acronym>
            <td class="number">50 000,-
    </table>
</div>
<div class="shadow" id="firmy">
    <h3>Velké firmy</h3>
    <table class="table-stripped table-hover">
        <tr>
            <td class="bold">Párátka s r.o.
                <acronym title="Luxury"><div class="icon-luxury"></div></acronym>
        <tr>
            <td class="bold">Třinecké železázny a.s.
                <acronym title="VIP"><div class="icon-vip"></div></acronym>
        <tr>
            <td class="bold">Novák motors s r.o.
                <acronym title="VIP"><div class="icon-vip"></div></acronym>
        <tr>
            <td class="bold">Plastové flašky o.s.
                <acronym title="VIP"><div class="icon-vip"></div></acronym>
    </table>
    
</div>
<div class="shadow" id="diskuze">
    <h3>Poslední příspěvky v diskuzi</h3>
    <table class="table-stripped table-hover">
        <tr>
            <th>Téma
            <th>Kategorie
            <th>Autor
            <th>Datum
        <tr>
            <td class="bold">Zend Framework 2 - pomůcka nebo přítež?
            <td>Web
            <td>Honza Novák
            <td>13. 9. 2015
        <tr>
            <td class="bold">Jak na zahradní jezídko
            <td>Zahrada
            <td>Jana Nováková
            <td>10. 9. 2015
        <tr>
            <td class="bold">Plovoučka nebo dlažba?
            <td>Domácnost
            <td>Marek Musil
            <td>8. 9. 2015
        <tr>
            <td class="bold">Otevření fotbalového hřiště
            <td>Sport
            <td>Pavel Volný
            <td>6. 9. 2015
    </table>
</div>
<div class="shadow" id="clanky">
    <h3>Poslední články</h3>
    <table class="table-stripped table-hover">
        <tr>
            <th>Titulek
            <th>Autor
            <th>Datum
        <tr>
            <td class="bold">28. ročník běhu na Kozubovou
            <td>Petr Novák
            <td>12. 9. 2015
        <tr>
            <td class="bold">Rekostrukce náměstí
            <td>Klára Nováková
            <td>3. 9. 2015
        <tr>
            <td class="bold">Výluka na ulici Nádražní
            <td>Adam Musil
            <td>27. 8. 2015
    </table>
    
</div>